#!/usr/bin/env python3
"""
Script to install the dependencies of all plugins or a specific plugin.
This script browses the requirements.txt files in each plugin directory
and installs the necessary dependencies.

Usage:
    python install_plugin_requirements.py [--plugin nom_plugin] [--dev]

Options:
    --plugin nom_plugin  Install only the dependencies of the specified plugin
    --dev                Install also development dependencies if present
"""
import os
import sys
import subprocess
import argparse
from pathlib import Path


def find_plugin_requirements(base_dir, plugin_name=None):
    """
    Find all requirements.txt files for plugins or a specific plugin.
    
    Args:
        base_dir (str): Base directory to search in
        plugin_name (str, optional): Specific plugin name
        
    Returns:
        list: List of paths to requirements.txt files
    """
    plugins_dir = os.path.join(base_dir, "app", "plugins")
    requirements_files = []
    
    if not os.path.isdir(plugins_dir):
        print(f"Le répertoire {plugins_dir} n'existe pas.")
        return requirements_files
    
    if plugin_name:
        plugin_path = os.path.join(plugins_dir, plugin_name)
        req_file = os.path.join(plugin_path, "requirements.txt")
        if os.path.isfile(req_file):
            requirements_files.append(req_file)
        dev_req_file = os.path.join(plugin_path, "requirements-dev.txt")
        if os.path.isfile(dev_req_file):
            requirements_files.append(("dev", dev_req_file))
    else:
        for plugin in os.listdir(plugins_dir):
            plugin_path = os.path.join(plugins_dir, plugin)
            if os.path.isdir(plugin_path):
                req_file = os.path.join(plugin_path, "requirements.txt")
                if os.path.isfile(req_file):
                    requirements_files.append(req_file)
                dev_req_file = os.path.join(plugin_path, "requirements-dev.txt")
                if os.path.isfile(dev_req_file):
                    requirements_files.append(("dev", dev_req_file))
    
    return requirements_files


def install_requirements(requirements_files, install_dev=False):
    """
    Install dependencies from requirements.txt files.
    
    Args:
        requirements_files (list): List of paths to requirements.txt files
        install_dev (bool): If True, install also development dependencies
    """
    for req_file in requirements_files:
        if isinstance(req_file, tuple) and req_file[0] == "dev":
            if install_dev:
                print(f"Installing development dependencies from {req_file[1]}...")
                subprocess.run([sys.executable, "-m", "pip", "install", "-r", req_file[1]])
        else:
            print(f"Installing dependencies from {req_file}...")
            subprocess.run([sys.executable, "-m", "pip", "install", "-r", req_file])


def generate_consolidated_requirements(base_dir, output_file="requirements-plugins.txt"):
    """
    Generate a consolidated requirements file with all plugin dependencies.
    
    Args:
        base_dir (str): Base directory
        output_file (str): Output file name
    """
    all_requirements = set()
    plugins_dir = os.path.join(base_dir, "app", "plugins")
    
    for plugin in os.listdir(plugins_dir):
        plugin_path = os.path.join(plugins_dir, plugin)
        if os.path.isdir(plugin_path):
            req_file = os.path.join(plugin_path, "requirements.txt")
            if os.path.isfile(req_file):
                with open(req_file, "r") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#"):
                            all_requirements.add(line)
    
    with open(os.path.join(base_dir, output_file), "w") as f:
        f.write("# This file is automatically generated by install_plugin_requirements.py\n")
        f.write("# It contains all plugin dependencies\n\n")
        for req in sorted(all_requirements):
            f.write(f"{req}\n")
    
    print(f"File {output_file} generated successfully.")


def main():
    parser = argparse.ArgumentParser(description="Install plugin dependencies")
    parser.add_argument("--plugin", help="Specific plugin to install")
    parser.add_argument("--dev", action="store_true", help="Install development dependencies")
    parser.add_argument("--generate", action="store_true", help="Generate a consolidated requirements file")
    args = parser.parse_args()
    
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    if args.generate:
        generate_consolidated_requirements(base_dir)
        return
    
    requirements_files = find_plugin_requirements(base_dir, args.plugin)
    
    if not requirements_files:
        if args.plugin:
            print(f"No requirements.txt found for plugin '{args.plugin}'.")
        else:
            print("No requirements.txt found in plugin directories.")
        return
    
    install_requirements(requirements_files, args.dev)
    print("Installation of plugin dependencies completed successfully.")


if __name__ == "__main__":
    main()
