"""
Pydantic schemas for the Advanced Internationalization plugin.
"""

from typing import Dict, List, Optional, Any, Union
from pydantic import BaseModel, Field, validator
from datetime import datetime


class LanguageBase(BaseModel):
    """Base schema for Language operations."""
    code: str = Field(..., description="ISO language code (e.g., 'en', 'fr')")
    name: str = Field(..., description="Language name in English (e.g., 'English', 'French')")
    native_name: str = Field(..., description="Language name in its native form (e.g., 'English', 'Français')")
    flag_code: Optional[str] = Field(None, description="Two-letter country code for flag display")
    is_rtl: bool = Field(False, description="Whether the language is written right-to-left")
    is_default: bool = Field(False, description="Whether this is the default fallback language")
    is_enabled: bool = Field(True, description="Whether this language is enabled")


class LanguageCreate(LanguageBase):
    """Schema for creating a new language."""
    pass


class LanguageUpdate(BaseModel):
    """Schema for updating an existing language."""
    code: Optional[str] = None
    name: Optional[str] = None
    native_name: Optional[str] = None
    flag_code: Optional[str] = None
    is_rtl: Optional[bool] = None
    is_default: Optional[bool] = None
    is_enabled: Optional[bool] = None


class Language(LanguageBase):
    """Schema for a complete language object with database fields."""
    id: int
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class TranslationGroupBase(BaseModel):
    """Base schema for TranslationGroup operations."""
    name: str = Field(..., description="Name of the translation group")
    description: Optional[str] = Field(None, description="Description of the translation group")


class TranslationGroupCreate(TranslationGroupBase):
    """Schema for creating a new translation group."""
    pass


class TranslationGroupUpdate(BaseModel):
    """Schema for updating an existing translation group."""
    name: Optional[str] = None
    description: Optional[str] = None


class TranslationGroup(TranslationGroupBase):
    """Schema for a complete translation group object with database fields."""
    id: int
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class PluralForm(BaseModel):
    """Schema for plural form variations."""
    quantity: str = Field(..., description="Plural form category (e.g., 'zero', 'one', 'two', 'few', 'many', 'other')")
    value: str = Field(..., description="Translated text for this plural form")


class TranslationBase(BaseModel):
    """Base schema for Translation operations."""
    key: str = Field(..., description="Translation key (e.g., 'app.welcome')")
    value: str = Field(..., description="Translated text")
    context: Optional[str] = Field(None, description="Optional context for disambiguation")
    plural_forms: Optional[List[PluralForm]] = Field(None, description="Optional plural forms")
    is_machine_translated: bool = Field(False, description="Whether this translation was generated by machine")
    needs_review: bool = Field(False, description="Whether this translation needs review")


class TranslationCreate(TranslationBase):
    """Schema for creating a new translation."""
    language_code: str = Field(..., description="Language code for this translation")
    group_name: str = Field(..., description="Group name for this translation")


class TranslationUpdate(BaseModel):
    """Schema for updating an existing translation."""
    key: Optional[str] = None
    value: Optional[str] = None
    context: Optional[str] = None
    plural_forms: Optional[List[PluralForm]] = None
    is_machine_translated: Optional[bool] = None
    needs_review: Optional[bool] = None


class Translation(TranslationBase):
    """Schema for a complete translation object with database fields."""
    id: int
    language: Language
    group: TranslationGroup
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class TranslationHistoryBase(BaseModel):
    """Base schema for TranslationHistory operations."""
    translation_id: int
    language_code: str
    key: str
    old_value: Optional[str] = None
    new_value: str
    user_id: Optional[int] = None


class TranslationHistory(TranslationHistoryBase):
    """Schema for a complete translation history object with database fields."""
    id: int
    created_at: datetime
    
    class Config:
        from_attributes = True


class TranslationStatistics(BaseModel):
    """Schema for translation statistics."""
    language_code: str
    language_name: str
    total_keys: int
    translated_keys: int
    missing_keys: int
    needs_review: int
    completion_percentage: float


class PluralRules(BaseModel):
    """Schema for plural rules by language."""
    language_code: str
    rules: Dict[str, str] = Field(..., description="Plural rules in ICU format")


class ImportResult(BaseModel):
    """Schema for import operation results."""
    added: int
    updated: int
    skipped: int
    errors: List[str]


class TranslationKey(BaseModel):
    """Schema representing a translation key with its values across languages."""
    key: str
    group: str
    translations: Dict[str, Union[str, Dict[str, Any]]]
    has_missing_translations: bool
