import { PluginsProvider } from "@/contexts/plugins"; 

export const metadata = {
  title: 'Kaapi Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
 
    <html lang="en">
      <body>
        <PluginsProvider>
          {children}
        </PluginsProvider>
      </body>
    </html>
    
  )
}
