"""Add sujet_cluster to Article model

Revision ID: 1985e5b8c1ac
Revises: 9d04d686013d
Create Date: 2025-09-30 13:10:01.523347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1985e5b8c1ac'
down_revision: Union[str, None] = '9d04d686013d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sujet_cluster', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_sujet_cluster'), ['sujet_cluster'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_sujet_cluster'))
        batch_op.drop_column('sujet_cluster')

    # ### end Alembic commands ###
