"""change_image_colum

Revision ID: 2407cc1f36bb
Revises: ab2632997ebb
Create Date: 2025-11-11 14:31:52.383988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2407cc1f36bb'
down_revision: Union[str, None] = 'ab2632997ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.JSON(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
