"""tekawake_modele

Revision ID: 5db57affab20
Revises: 6b0d804ab415
Create Date: 2025-11-25 17:25:41.091250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5db57affab20'
down_revision: Union[str, None] = '6b0d804ab415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('veilles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veilles_id'), ['id'], unique=False)

    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary_article', sa.Text(), nullable=True),
    sa.Column('slides', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clusters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clusters_is_published'), ['is_published'], unique=False)

    # Add the column as nullable first
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veille_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cluster_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('source_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scraping_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('processing_error', sa.Text(), nullable=True))

    # Create a default veille and get its id
    veilles_table = sa.table('veilles',
                             sa.column('id', sa.Integer),
                             sa.column('prompt', sa.Text))
    op.bulk_insert(veilles_table, [{'prompt': 'Default Veille'}])
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT id FROM veilles WHERE prompt = 'Default Veille'"))
    default_veille_id = result.scalar()

    # Update existing articles with a default value for veille_id, source_url and source_name
    op.execute(f"UPDATE articles SET veille_id = {default_veille_id} WHERE veille_id IS NULL")
    op.execute("UPDATE articles SET source_url = 'http://example.com/' || id WHERE source_url IS NULL")
    op.execute("UPDATE articles SET source_name = 'example' WHERE source_name IS NULL")


    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('veille_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('source_url', existing_type=sa.String(length=1024), nullable=False)
        batch_op.alter_column('source_name', existing_type=sa.String(length=100), nullable=False)
        batch_op.drop_index(batch_op.f('ix_articles_day_category'))
        batch_op.drop_index(batch_op.f('ix_articles_published'))
        batch_op.drop_index(batch_op.f('ix_articles_sujet_cluster'))
        batch_op.drop_index(batch_op.f('ix_articles_url'))
        batch_op.create_index(batch_op.f('ix_articles_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_processed'), ['is_processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_source_url'), ['source_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_veille_id'), ['veille_id'], unique=False)
        batch_op.create_foreign_key(None, 'clusters', ['cluster_id'], ['id'])
        batch_op.create_foreign_key(None, 'veilles', ['veille_id'], ['id'])
        batch_op.drop_column('sujet_cluster')
        batch_op.drop_column('day_category')
        batch_op.drop_column('date')
        batch_op.drop_column('error')
        batch_op.drop_column('slides')
        batch_op.drop_column('analysis_date')
        batch_op.drop_column('summary_article')
        batch_op.drop_column('published')
        batch_op.drop_column('source')
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('summary_article', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('analysis_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('slides', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('day_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sujet_cluster', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_veille_id'))
        batch_op.drop_index(batch_op.f('ix_articles_source_url'))
        batch_op.drop_index(batch_op.f('ix_articles_is_processed'))
        batch_op.drop_index(batch_op.f('ix_articles_cluster_id'))
        batch_op.create_index(batch_op.f('ix_articles_url'), ['url'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_sujet_cluster'), ['sujet_cluster'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_day_category'), ['day_category'], unique=False)
        batch_op.drop_column('processing_error')
        batch_op.drop_column('is_processed')
        batch_op.drop_column('scraping_date')
        batch_op.drop_column('source_name')
        batch_op.drop_column('source_url')
        batch_op.drop_column('cluster_id')
        batch_op.drop_column('veille_id')

    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_is_published'))
        batch_op.drop_index(batch_op.f('ix_clusters_id'))
        batch_op.drop_index(batch_op.f('ix_clusters_category_id'))

    op.drop_table('clusters')
    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veilles__id'))

    op.drop_table('veilles')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###