"""update article model for veille plugin

Revision ID: 9d04d686013d
Revises: 965fa884bee0
Create Date: 2025-09-26 11:20:14.518446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d04d686013d'
down_revision: Union[str, None] = '965fa884bee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('score_pertinence', sa.Integer(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_score_pertinence'), ['score_pertinence'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url'), ['url'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_url'))
        batch_op.drop_index(batch_op.f('ix_articles_score_pertinence'))
        batch_op.drop_index(batch_op.f('ix_articles_published'))
        batch_op.drop_index(batch_op.f('ix_articles_id'))

    op.drop_table('articles')
    # ### end Alembic commands ###
