"""add unread_count to user_conversation_settings

Revision ID: a47cc3b0ecbd
Revises: 22950a05c8c9
Create Date: 2025-03-23 14:18:20.713714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47cc3b0ecbd'
down_revision: Union[str, None] = '22950a05c8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messaging_user_conversation_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unread_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messaging_user_conversation_settings', schema=None) as batch_op:
        batch_op.drop_column('unread_count')

    # ### end Alembic commands ###
