"""add_category_day

Revision ID: ab2632997ebb
Revises: c41650372cf6
Create Date: 2025-11-10 10:14:01.976601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2632997ebb'
down_revision: Union[str, None] = 'c41650372cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_day_category'), ['day_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_day_category'))
        batch_op.drop_column('day_category')

    # ### end Alembic commands ###
