"""Add push subscriptions table

Revision ID: ab2f80a8346b
Revises: a47cc3b0ecbd
Create Date: 2025-03-25 13:34:41.923198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2f80a8346b'
down_revision: Union[str, None] = 'a47cc3b0ecbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
