"""Add llm_provider to Veille

Revision ID: b1a33ebdefe9
Revises: 1785abbea2c5
Create Date: 2026-05-19 10:14:17.943646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a33ebdefe9'
down_revision: Union[str, None] = '1785abbea2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_provider', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_veilles_llm_provider'), ['llm_provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veilles_llm_provider'))
        batch_op.drop_column('llm_provider')

    # ### end Alembic commands ###
