"""add image and dateTime

Revision ID: c41650372cf6
Revises: 93a04e6e1013
Create Date: 2025-11-06 11:02:47.402766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41650372cf6'
down_revision: Union[str, None] = '93a04e6e1013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=2048), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_publication_date'), ['publication_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_publication_date'))
        batch_op.drop_column('image_url')
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###
