"""add status veille

Revision ID: df4ceea93754
Revises: 5db57affab20
Create Date: 2025-11-27 16:18:17.609122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4ceea93754'
down_revision: Union[str, None] = '5db57affab20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Étape 1: Ajouter les colonnes en tant que nullable
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.Text(), nullable=True))

    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_message', sa.Text(), nullable=True))

    # Étape 2: Mettre à jour les données existantes avec une valeur par défaut
    op.execute("UPDATE articles SET status = 'PENDING' WHERE status IS NULL")
    op.execute("UPDATE veilles SET status = 'PENDING' WHERE status IS NULL")

    # Étape 3: Modifier les colonnes pour qu'elles soient non-nullable
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=50), nullable=False)
        batch_op.drop_index(batch_op.f('ix_articles_is_processed'))
        batch_op.drop_index(batch_op.f('ix_articles_score_pertinence'))
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)
        batch_op.drop_column('processing_error')
        batch_op.drop_column('score_pertinence')
        batch_op.drop_column('is_processed')

    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veilles', schema=None) as batch_op:
        batch_op.drop_column('status_message')
        batch_op.drop_column('status')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score_pertinence', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.create_index(batch_op.f('ix_articles_score_pertinence'), ['score_pertinence'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_processed'), ['is_processed'], unique=False)
        batch_op.drop_column('status_message')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
