#!/bin/bash

# Script to generate varied audit events for testing Grafana dashboard

# Number of audit events to generate
count=${1:-50}

# Types of resources
resources=("user" "order" "product" "payment" "session" "file" "report" "setting")

# Types of actions
actions=("create" "update" "delete" "view" "export" "import" "approve" "reject")

echo "Generating $count audit events..."

progress=0
for ((i=1; i<=$count; i++)); do
    # Randomly select a resource and action
    resource=${resources[$RANDOM % ${#resources[@]}]}
    action=${actions[$RANDOM % ${#actions[@]}]}
    
    # Generate a random user ID between 1 and 100
    user_id=$(($RANDOM % 100 + 1))
    
    # Generate the current timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    # Generate a random IP address
    ip="192.168.0.$(($RANDOM % 255 + 1))"
    
    # Send the audit event to the API
    response=$(curl -s -X POST "http://localhost:8000/plugins/advanced_audit/logs" \
        -H "Content-Type: application/json" \
        -d "{\"user_id\": $user_id, \"action\": \"$action\", \"resource\": \"$resource\", \"details\": \"Generated by script at $timestamp from IP $ip\"}")
    
    echo "Audit event sent: [$resource] $action by user $user_id"
    
    # Update progress
    progress=$((progress + 1))
    if [ $((progress % 10)) -eq 0 ]; then
        echo "Progress: $progress/$count events generated"
    fi
    
    # Small pause to avoid overloading the API
    sleep 0.2
done

echo "Completed! $count audit events generated and sent to the API."
